[tool.black]
line-length = 100
target_version = ['py311']
include = '\.pyi?$'

[tool.ruff]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "C",  # flake8-comprehensions
    "B",  # flake8-bugbear
]

ignore = [
    "E501",  # line too long, handled by black
    "B008",  # do not perform function calls in argument defaults
    # "C901",  # complexity
]
show-fixes = true

target-version = "py311"

[tool.mypy]
ignore_missing_imports = true

[tool.pytest.ini_options]
python_files ="test*.py"
testpaths = [
    "tests"
]